#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export WEKAPP_PATH=$WEKA
export WEKA_TEKA_COMMAND=./teka.py
export WEKA_PAGER="slit --debug --always-term"
export PAGER=slit
export WEKA_NO_PATCHING_WARNINGS=1
export PATH="/usr/local/opt/mysql-client/bin:$PATH"
